// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8MBuFNTAdpMP0j5y7Oe5K9HnoprsWuoM',
    appId: '1:965237210463:web:3f09ea1ef68e44b3550aea',
    messagingSenderId: '965237210463',
    projectId: 'smsbahga',
    authDomain: 'smsbahga.firebaseapp.com',
    databaseURL: 'https://smsbahga-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smsbahga.firebasestorage.app',
    measurementId: 'G-X6NQG5JQ9P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4WB7T6S-N8ehNJCF6FQOsQzVkRNX9gc4',
    appId: '1:965237210463:android:2ff211c04d1fb62f550aea',
    messagingSenderId: '965237210463',
    projectId: 'smsbahga',
    databaseURL: 'https://smsbahga-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smsbahga.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYBOXiyuHJC7dW0CVIhqSMbb_8mfjd620',
    appId: '1:965237210463:ios:16450a3afc7e7ea4550aea',
    messagingSenderId: '965237210463',
    projectId: 'smsbahga',
    databaseURL: 'https://smsbahga-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smsbahga.firebasestorage.app',
    iosBundleId: 'com.example.gpSprint1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYBOXiyuHJC7dW0CVIhqSMbb_8mfjd620',
    appId: '1:965237210463:ios:16450a3afc7e7ea4550aea',
    messagingSenderId: '965237210463',
    projectId: 'smsbahga',
    databaseURL: 'https://smsbahga-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smsbahga.firebasestorage.app',
    iosBundleId: 'com.example.gpSprint1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8MBuFNTAdpMP0j5y7Oe5K9HnoprsWuoM',
    appId: '1:965237210463:web:e8e4ea1fcf372c37550aea',
    messagingSenderId: '965237210463',
    projectId: 'smsbahga',
    authDomain: 'smsbahga.firebaseapp.com',
    databaseURL: 'https://smsbahga-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smsbahga.firebasestorage.app',
    measurementId: 'G-76B3VHSD73',
  );

}